## Assignment 1

In [533]:
from pprint import pprint

Using this to print some of the dictionaries in a more nice way

### Task 1: A list of dictionaries 


In [537]:
#data with transactions for Task 1
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

a) Filter out invalid transactions with price 0 or a negative amount of transactions

In [540]:
#creating a new dictionary called validtransactions by filtering transactions using a for loop and if statement
validtransactions = [
    t for t in transactions 
        if t["price"] > 0 and t["quantity"] >= 0
]
        

In [542]:
pprint(validtransactions)

[{'id': 1, 'price': 1200, 'product': 'Laptop', 'quantity': 2, 'region': 'EU'},
 {'id': 4, 'price': 350, 'product': 'Monitor', 'quantity': 3, 'region': 'US'},
 {'id': 5, 'price': 1200, 'product': 'Laptop', 'quantity': 1, 'region': 'EU'},
 {'id': 6,
  'price': 75,
  'product': 'Keyboard',
  'quantity': 10,
  'region': 'APAC'}]


b) Creating the field quantity

In [547]:
#adding a new field with a for loop 
for t in validtransactions:
    t["total"] = t["price"] * t["quantity"]

In [549]:
pprint(validtransactions)

[{'id': 1,
  'price': 1200,
  'product': 'Laptop',
  'quantity': 2,
  'region': 'EU',
  'total': 2400},
 {'id': 4,
  'price': 350,
  'product': 'Monitor',
  'quantity': 3,
  'region': 'US',
  'total': 1050},
 {'id': 5,
  'price': 1200,
  'product': 'Laptop',
  'quantity': 1,
  'region': 'EU',
  'total': 1200},
 {'id': 6,
  'price': 75,
  'product': 'Keyboard',
  'quantity': 10,
  'region': 'APAC',
  'total': 750}]


c) Group transaction by region and calculate the total revenue per region

In [552]:
regional_totals = {} #here the totals from the regions will be stored

for t in validtransactions: 
    region = t["region"]
    total = t["total"]

    if region in regional_totals:        # adding the totals from the regions
            regional_totals[region]+= total 
    else: 
        regional_totals[region] = total 


In [554]:
pprint(regional_totals)

{'APAC': 750, 'EU': 3600, 'US': 1050}


The transactions are grouped based on region by using a for loop and an if statement. The if statement checks if there exists a list with that region in the dictionary regional_total and adds the total from the region to the already existing ones. If there does not exist any, the if statement adds the new region to the dictionary. 


d) Printing the region with the highest total revenue 


In [558]:
max_total = max(regional_totals.values())

for reg in regional_totals: 
    if regional_totals[reg] == max_total: 
        print(f"The region with the highest total revenue is {reg} with a total revenue of {max_total}") 

The region with the highest total revenue is EU with a total revenue of 3600


Task 2: Creating a function

In [561]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

In [563]:
def summarise_sales(sales):
    total_sales = sum(sales)
    average_sales = sum(sales)/len(sales)
    best_day = sales.index(max(sales)) + 1 #adding the + 1 to make results more logical since python starts indexing from 0 
    worst_day = sales.index(min(sales)) + 1 #adding the + 1 to make results more logical since python starts indexing from 0 
    above_average = sum(1 for sale in sales if sale > average_sales) #counting the sales that are fulfilling the condition and then assigning them with 1 

    #storing the values from the function in a dictonary
    return {
        "total": total_sales,
        "average": average_sales,
        "best_day": best_day,
        "worst_day": worst_day,
        "above_average_count": above_average
    } 

In [565]:
summary = summarise_sales(sales)
pprint(summary)

{'above_average_count': 7,
 'average': 1465.0,
 'best_day': 11,
 'total': 20510,
 'worst_day': 4}


### Task 3: Loops

In [568]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

a) Creating a new list of only passing students

In [571]:
passing = [
    s for s in students if s["grade"] >= 50  
]

In [573]:
pprint(passing)

[{'attendance': 0.92, 'grade': 85, 'name': 'Anna'},
 {'attendance': 0.75, 'grade': 58, 'name': 'Erik'},
 {'attendance': 0.98, 'grade': 91, 'name': 'Mia'},
 {'attendance': 0.88, 'grade': 72, 'name': 'Sara'},
 {'attendance': 0.7, 'grade': 67, 'name': 'Tom'},
 {'attendance': 0.99, 'grade': 95, 'name': 'Nina'},
 {'attendance': 0.65, 'grade': 50, 'name': 'Olli'}]


b) Print grades


In [576]:
for s in students:
    if s["grade"] >= 80: 
        s["score"] = "Excellent" 
    elif s["grade"] >= 50 and s["grade"] <= 79:
        s["score"] = "Pass" 
    else:
        s["score"] = "Fail" 

for s in students:
    print(f"{s["name"]} : {s["score"]}")

Anna : Excellent
Erik : Pass
Mia : Excellent
Leo : Fail
Sara : Pass
Tom : Pass
Nina : Excellent
Olli : Pass


c) counting attendance rate under 0.80 

In [579]:
low_attendance = sum(1 for s in students if s["attendance"] < 0.80) #assigning the students that fulfill the condition with 1 and then counting them 
print(low_attendance)
    

4


d) Find the student with the highest grade 

In [582]:
#creating the variables
highest_grade = 0
top_student = None 

#looping through the variables
for s in students: 
    if s["grade"] > highest_grade: 
        highest_grade = s["grade"]
        top_student = s

#printing the results
print(f"{top_student["name"]} has the grade {highest_grade}!")

Nina has the grade 95!


e) Find the student with the highest grade using max()

In [585]:
best_student = max(students, key = lambda s: s["grade"])
print(f"{best_student["name"]} has the grade {best_student["grade"]}!")

Nina has the grade 95!


When using the key = lambda s: s["grade"] tells the max() function to use grade as the value for the comparison. 

### Task 4: Class and methods 

In [589]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

a) Adding method

In [592]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}
        
#a) method for adding a new asset
    def add_asset(ticker, shares, price_per_share): 
        if ticker in self.holdings: 
            self.holdnings[ticker]["shares"] += shares
            self.holdings[ticker]["price_per_share"] = price_per_share
        else:
            self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share}
        

b) Adding total value method

In [595]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    def add_asset(self, ticker, shares, price_per_share): 
        if ticker in self.holdings: 
            self.holdings[ticker]["shares"] += shares
            self.holdings[ticker]["price_per_share"] = price_per_share
        else:
            self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share}

#b) method for total value 
    def total_value(total):
        total = 0 
        for asset in self.holdings.values():
            total =+ asset["shares"]*asset["price_per_share"]
        return total

c) Adding method that returns highest total value 

In [598]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    def add_asset(self, ticker, shares, price_per_share): 
        if ticker in self.holdings: 
            self.holdings[ticker]["shares"] += shares
            self.holdings[ticker]["price_per_share"] = price_per_share
        else:
            self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share}

    def total_value(total):
        total = 0 
        for asset in self.holdings.values():
            total =+ asset["shares"]*asset["price_per_share"]
        return total
        
#c) method that returns asset with the highest total value
    def most_valuable(self):
        best_ticker = None
        best_value = 0
        for ticker, asset in self.holdings.items(): 
            value = asset["shares"] * asset["price_per_share"]
            if value > best_value: 
                best_value = value 
                best_ticker = ticker 
            return best_ticker
        

d) Returning a summery of the portfolio 

In [601]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    def add_asset(self, ticker, shares, price_per_share): 
        if ticker in self.holdings: 
            self.holdings[ticker]["shares"] += shares
            self.holdings[ticker]["price_per_share"] = price_per_share
        else:
            self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share}

    def total_value(self):
        total = 0 
        for asset in self.holdings.values():
            total += asset["shares"]*asset["price_per_share"]
        return total

    def most_valuable(self):
        best_ticker = None
        best_value = 0
        for ticker, asset in self.holdings.items(): 
            value = asset["shares"] * asset["price_per_share"]
            if value > best_value: 
                best_value = value 
                best_ticker = ticker 
            return best_ticker
            
#d) 
    def __str__(self):
        return f"Owner: {self.owner}, Asset: {len(self.holdings)}, Total Value: {self.total_value()}"

Creating an instance to demonstrate the methods.

In [604]:
#creating the instance
p = Portfolio("Mia")
p.add_asset("GOOGL", 5, 400)
p.add_asset("AAPL", 6, 200)
p.add_asset("MSFT", 8, 150)

#demonstrating the methods
print(p.total_value())
print(p.most_valuable())
print(p)

4400
GOOGL
Owner: Mia, Asset: 3, Total Value: 4400


### Task 5: Importing a module 

In [607]:
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

In [609]:
from datetime import datetime

#converting the list into a date object 
dates = [datetime.strptime(order[0], "%Y-%m-%d").date() for order in orders]

#finding the first and last date and the calculating the difference
earliest = min(dates)
latest = max(dates)

difference = latest - earliest

print(f"Earliest order: {earliest}")
print(f"Latest order: {latest}")
print(f"Days between: {difference.days} days")


Earliest order: 2025-01-15
Latest order: 2025-04-05
Days between: 80 days


### Task 6: Array Operations and Broadcasting

In [612]:
import numpy as np
# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

a) Total annual revenue for each year

In [615]:
#calculating the annual_revenue per row
annual_revenue = revenue.sum(axis = 1)
print(annual_revenue)

[ 880  950 1080]


b) Mean quarterly revenue across all years 

In [618]:
#calculating the quarterly mean from the columns 
quarterly_mean = revenue.mean(axis = 0)
print(quarterly_mean)

[226.66666667 260.         206.66666667 276.66666667]


c) Growth adjustment to 2024

In [621]:
#creating an array for the growth and multiplying it with the row for 2024 
growth = np.array([1.05, 1.03, 1.08, 1.02])
adjusted_2024 = revenue[2] * growth
print(adjusted_2024)

[262.5 298.7 248.4 316.2]


d) Print all quarterly revenue values that exceed 250

In [624]:
exceeds_250 = revenue[revenue > 250]
print(exceeds_250)

[260 270 290 310]


### Task 7: Pandas

In [627]:
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}


a) Create DataFrame

In [630]:
df = pd.DataFrame(data)
df["salary_per_year_exp"] = (df["salary"]/df["years_exp"]).round()

b) Sort DataFrame and print top 3 employees

In [633]:
sorted_df = df.sort_values("performance_score", ascending = False) #ascending = False to get the descending order
print(sorted_df.head(3))  #head(3) gives the three highest values 

  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                638.0  
2                686.0  
0                900.0  


c) Select all employees in the Finance department with a performance score above 4.0

In [636]:
finance_high = df.loc[(df["department"] == "Finance") & (df["performance_score"] > 4.0)]
print(finance_high)

  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   

   salary_per_year_exp  
0                900.0  
2                686.0  


d) Rename a column

In [639]:
df = df.rename(columns = {"years_exp" : "experience_years"})
print(df.columns) #printing the name of all columns to see that the name is changed 

Index(['employee', 'department', 'salary', 'experience_years',
       'performance_score', 'salary_per_year_exp'],
      dtype='object')


e) Select and print the salary and performance score columns for the first four employees 

In [642]:
print(df.iloc[:4,[2,4]]) #:4 signifies rows and 2, 4 signifies column position 2 and 4 

   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0


### Task 8: More Pandas 

In [645]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

a) Create DataFrame

In [648]:
df_traffic = pd.DataFrame({
    "date": days, 
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
})

df_traffic = df_traffic.set_index("date")

print(df_traffic)

            visitors  conversion_rate  avg_order_value
date                                                  
2025-01-06       206           0.0645            64.30
2025-01-07       472           0.0578            48.44
2025-01-08       437           0.0756            43.26
2025-01-09       221           0.0339            43.61
2025-01-10       563           0.0679            49.39
2025-01-11       288           0.0511            46.07
2025-01-12       302           0.0339            72.90
2025-01-13       273           0.0300            42.82
2025-01-14       333           0.0499            50.33
2025-01-15       270           0.0550            50.28
2025-01-16       339           0.0311            50.28
2025-01-17       524           0.0209            50.55
2025-01-18       380           0.0483            45.18
2025-01-19       569           0.0637            44.17
2025-01-20       379           0.0751            41.38
2025-01-21       310           0.0575            35.12
2025-01-22

b) Compute two new columns

In [651]:
#computing conversions and creating the column, using round to round the value to nearest integer
df_traffic["conversions"] = (df_traffic["visitors"] * df_traffic["conversion_rate"]).round()

#computing daily revenue and creating the coulumn
df_traffic["daily_revenue"] = (df_traffic["conversions"] * df_traffic["avg_order_value"])

print(df_traffic[["conversions", "daily_revenue"]])

            conversions  daily_revenue
date                                  
2025-01-06         13.0         835.90
2025-01-07         27.0        1307.88
2025-01-08         33.0        1427.58
2025-01-09          7.0         305.27
2025-01-10         38.0        1876.82
2025-01-11         15.0         691.05
2025-01-12         10.0         729.00
2025-01-13          8.0         342.56
2025-01-14         17.0         855.61
2025-01-15         15.0         754.20
2025-01-16         11.0         553.08
2025-01-17         11.0         556.05
2025-01-18         18.0         813.24
2025-01-19         36.0        1590.12
2025-01-20         28.0        1158.64
2025-01-21         18.0         632.16
2025-01-22         39.0        2034.24
2025-01-23         38.0        2273.92
2025-01-24         18.0         802.26
2025-01-25         40.0        1776.40
2025-01-26         13.0         608.92
2025-01-27         15.0         680.85
2025-01-28         21.0         748.44
2025-01-29         21.0  

In [653]:
#the whole data frame for company website traffic after the changes 

print(df_traffic)

            visitors  conversion_rate  avg_order_value  conversions  \
date                                                                  
2025-01-06       206           0.0645            64.30         13.0   
2025-01-07       472           0.0578            48.44         27.0   
2025-01-08       437           0.0756            43.26         33.0   
2025-01-09       221           0.0339            43.61          7.0   
2025-01-10       563           0.0679            49.39         38.0   
2025-01-11       288           0.0511            46.07         15.0   
2025-01-12       302           0.0339            72.90         10.0   
2025-01-13       273           0.0300            42.82          8.0   
2025-01-14       333           0.0499            50.33         17.0   
2025-01-15       270           0.0550            50.28         15.0   
2025-01-16       339           0.0311            50.28         11.0   
2025-01-17       524           0.0209            50.55         11.0   
2025-0